name: qr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - pandas>=2.0.0
  - numpy>=1.24.0
  - aiohttp>=3.8.0
  - pip
  - pip:
    - ccxt>=4.0.0
    - aiofiles>=23.0.0
    - aiolimiter>=1.1.0
    - tenacity>=8.0.0
    - pytest>=7.0.0